name: $(BuildID)
trigger:
  batch: true
  branches:
    include:
    - master
pool:
  vmImage: windows-latest
resources:
  repositories:
  - repository: ProvisioningEngine
    name: CCAPractice/ProvisioningEngine
    type: github
    endpoint: githubconnection
    ref: master
  - repository: ProvisioningEngineTemplates
    name: CCAPractice/ProvisioningEngineTemplates
    type: github
    endpoint: githubconnection
    ref: master
extends:
  template: /pipelines/templates/common-infra-initiator.yaml@ProvisioningEngine
  parameters:
    provisioningEnvironment:
    - DEV
    - TST
    variableFiles:
    - /azure-pipelines/vars/common.yaml@self
    - /azure-pipelines/vars/{environment}.yaml@Self
    runScript: false
    templatetype: bicep
    # scriptsList:
    # - displayName: Running Powershell Script - Test1.ps1
    #   type: powerShell
    #   scriptName: test.ps1
    #   scriptArguments: ""
