variables:
# TAGS
  serviceCodeTag: PEGT
  serviceNameTag: PEGT
  serviceTypeTag: LOB
  projectName: GPE 
  EnvironmentName: "$(deploymentEnvironment)"
  azureResourceManagerConnection: 'genericTool'
  subscriptionName: 'DevSubscription'
  subscriptionId: 'c98f771e-214d-4c3e-ac95-31fbd563bd0d'
  servicesLocation: 'UK South' #Deployment Location in Azure
  deploy: 'true'
  postFixResourceGroupNumber: 1401
  postFixEventTopicNumber: 1401
  postFixAppinsightsNumber: 1401
  networkResourceGroupName: '$(deploymentEnvironment)$(projectName)$(nc-function-network)$(nc-resource-resourcegroup)$(postFixResourceGroupNumber)'
  dataBaseResourceGroupName: '$(deploymentEnvironment)$(projectName)$(nc-function-database)$(nc-resource-resourcegroup)$(postFixResourceGroupNumber)'
  storageResourceGroupName: '$(deploymentEnvironment)$(projectName)$(nc-function-soc)$(nc-resource-resourcegroup)$(postFixResourceGroupNumber)'
  otherInfraResourceGroupName: '$(deploymentEnvironment)$(projectName)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(postFixResourceGroupNumber)'
  otherResourceGroupName: '$(deploymentEnvironment)$(projectName)$(nc-function-additional)$(nc-resource-resourcegroup)$(postFixResourceGroupNumber)'
  servicesToDeploy: INF_event-topic,NET_app-insight #event-topic,_event-topic,event-topic,NET_cost-management-dashboard,INF_event-topic #add type of Infra as pre-fix for service provisioning
  dashboardName: ''
  budgetName: 'cost-management-dashboard-budget'
  budgetAmount: '1500'
  serviceCode: '$(serviceCodeTag)$(serviceNameTag)$(serviceTypeTag)'
  
#Resource Deployment Parameters

#EventTopic
  eventTopicName: '$(deploymentEnvironment)$(projectName)$(nc-function-infrastructure)$(nc-resource-eventtopic)$(postFixEventTopicNumber)'

#AppInsight
  appInsightsName: '$(deploymentEnvironment)$(projectName)$(nc-function-infrastructure)$(nc-resource-appinsights)$(postFixAppinsightsNumber)'
  appInsightsWorkspaceName: '$(deploymentEnvironment)$(projectName)$(nc-function-infrastructure)$(nc-resource-operationalinsights-workspace)$(postFixAppinsightsNumber)'

  
